### DISCUSSION TITLE
Game List

### DISCUSSION THREAD

**Discussion by woile** [Whisky-App/Whisky#348] [Ideas]
Is there a place where users can find information about games and also to add reports of how games work?
Something similar to https://www.protondb.com/

This thread could be a good starting point, so if anyone wants to report go ahead.

I'd recommend following this format:

```
game: xxx
status: platinum | gold | silver | bronze | borked
mac: <model>
gptk: ..
installs: yes | no
opens: yes | no
comments: ...
```

---

```yaml
game: mass effect andromeda
status: borked
mac: MacBook Pro 2019 i9
gptk: 0.3
installs: yes (steam)
opens: no
comments: EA installer is the problem
```

```yaml
game: doom eternal
status: borked
mac: MacBook Pro 2019 i9
gptk: 1.0.4
wine: 7.7.0
installs: yes (steam)
opens: no
comments: I see nothing
```
